# Generated by Django 5.1.2 on 2024-10-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
