# Generated by Django 5.1.2 on 2024-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
