# Generated by Django 5.1.2 on 2024-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
